name: Build and Deploy to OpenShift Sandbox

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/matapp:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/matapp:latest

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login to OpenShift
        run: |
          oc login ${{ secrets.OC_SERVER }} --token=${{ secrets.OC_TOKEN }}

      - name: Set OpenShift project
        run: |
          oc project ${{ secrets.OC_NAMESPACE }}

      - name: Deploy to OpenShift
        run: |
          oc delete all -l app=matapp || true
          oc new-app --docker-image=${{ secrets.DOCKERHUB_USERNAME }}/matapp:latest --name=matapp
          oc expose svc/matapp
